#!/bin/bash

this_dir=$(dirname $0)
output=$(${this_dir}/patchy-format.py 2>&1)
if (( $? == 0 )); then
    if [ -n "$output" ]; then
        echo Reformatted hunks of $(echo $output | tr "\n" ", "). Naughty ${USER}\!
        IFS="
"
        for filename in $output; do
            git add $filename
        done
    fi
else
    echo "Something went wrong with patchy-format:"
    echo -e $output
    exit 1
fi
